# Generated by Django 3.2.8 on 2021-11-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_auto_20211124_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='vaccine_name',
        ),
    ]
