# Generated by Django 3.2.8 on 2021-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_rename_notes_appointment_vaccine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected'), ('vaccinated', 'vaccinated'), ('Waitinglist for vaccine', 'Waiting list for vaccine')], default='Pending', max_length=50),
        ),
    ]
