# Generated by Django 3.2.8 on 2021-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
